### ISSUE TITLE
Crash on opening installer

### ISSUE THREAD

**Issue by MichaelJBerk** [Engelshell/armori#1]
After dragging the app to my Applications folder, I get the error that the app "is damaged and can't be opened"

**Workaround**
Using `xattr -cr` on the app seems to fix the issue

**Comment by MichaelJBerk** [comment]
Upon further googling around, the issue might be caused due to some signing issue: https://developer.apple.com/forums/thread/692774?answerId=692180022#692180022

**Comment by MichaelJBerk** [comment]
Even if I right-click the app and click “Open” to bypass gatekeeper, it still won’t run. I know that `xattr` can show a file’s extended attributes (which is where Gatekeeper stores the flags an for app), so it might be a good idea to see what listing them on your machine does.

**Comment by Engelshell** [comment]
Closing this because testing across multiple installs appears to work correctly. If there's future issues feel free to make another issue/reopen.
